name: Pretty HTML

on:
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Find and Remove </source> Tags
        run:  find . -type f -name "*.html" -exec sed -i 's/<\/source>//g' {} +

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Removed </source> tags from HTML files" || echo "No changes to commit"
          git push